package notes

import "machine/usb/hid/keyboard"

const Shift = keyboard.KeyLeftShift

// keymap for US English (international) keyboard
var keymap = [][]keyboard.Keycode{
	/*     */ {keyboard.KeySpace},
	/*  !  */ {Shift, keyboard.Key1},
	/*  "  */ {Shift, keyboard.KeyQuote},
	/*  #  */ {Shift, keyboard.Key3},
	/*  $  */ {Shift, keyboard.Key4},
	/*  %  */ {Shift, keyboard.Key5},
	/*  &  */ {Shift, keyboard.Key7},
	/*  '  */ {keyboard.KeyQuote},
	/*  (  */ {Shift, keyboard.Key9},
	/*  )  */ {Shift, keyboard.Key0},
	/*  *  */ {Shift, keyboard.Key8},
	/*  +  */ {Shift, keyboard.KeyEqual},
	/*  ,  */ {keyboard.KeyComma},
	/*  -  */ {keyboard.KeyMinus},
	/*  .  */ {keyboard.KeyPeriod},
	/*  /  */ {keyboard.KeySlash},
	/*  0  */ {keyboard.Key0},
	/*  1  */ {keyboard.Key1},
	/*  2  */ {keyboard.Key2},
	/*  3  */ {keyboard.Key3},
	/*  4  */ {keyboard.Key4},
	/*  5  */ {keyboard.Key5},
	/*  6  */ {keyboard.Key6},
	/*  7  */ {keyboard.Key7},
	/*  8  */ {keyboard.Key8},
	/*  9  */ {keyboard.Key9},
	/*  :  */ {Shift, keyboard.KeySemicolon},
	/*  ;  */ {keyboard.KeySemicolon},
	/*  <  */ {Shift, keyboard.KeyComma},
	/*  =  */ {keyboard.KeyEqual},
	/*  >  */ {Shift, keyboard.KeyPeriod},
	/*  ?  */ {Shift, keyboard.KeySlash},
	/*  @  */ {Shift, keyboard.Key2},
	/*  A  */ {Shift, keyboard.KeyA},
	/*  B  */ {Shift, keyboard.KeyB},
	/*  C  */ {Shift, keyboard.KeyC},
	/*  D  */ {Shift, keyboard.KeyD},
	/*  E  */ {Shift, keyboard.KeyE},
	/*  F  */ {Shift, keyboard.KeyF},
	/*  G  */ {Shift, keyboard.KeyG},
	/*  H  */ {Shift, keyboard.KeyH},
	/*  I  */ {Shift, keyboard.KeyI},
	/*  J  */ {Shift, keyboard.KeyJ},
	/*  K  */ {Shift, keyboard.KeyK},
	/*  L  */ {Shift, keyboard.KeyL},
	/*  M  */ {Shift, keyboard.KeyM},
	/*  N  */ {Shift, keyboard.KeyN},
	/*  O  */ {Shift, keyboard.KeyO},
	/*  P  */ {Shift, keyboard.KeyP},
	/*  Q  */ {Shift, keyboard.KeyQ},
	/*  R  */ {Shift, keyboard.KeyR},
	/*  S  */ {Shift, keyboard.KeyS},
	/*  T  */ {Shift, keyboard.KeyT},
	/*  U  */ {Shift, keyboard.KeyU},
	/*  V  */ {Shift, keyboard.KeyV},
	/*  W  */ {Shift, keyboard.KeyW},
	/*  X  */ {Shift, keyboard.KeyX},
	/*  Y  */ {Shift, keyboard.KeyY},
	/*  Z  */ {Shift, keyboard.KeyZ},
	/*  [  */ {keyboard.KeyLeftBrace},
	/*  \  */ {keyboard.KeyBackslash},
	/*  ]  */ {keyboard.KeyRightBrace},
	/*  ^  */ {Shift, keyboard.Key6},
	/*  _  */ {Shift, keyboard.KeyMinus},
	/*  `  */ {keyboard.KeyTilde},
	/*  a  */ {keyboard.KeyA},
	/*  b  */ {keyboard.KeyB},
	/*  c  */ {keyboard.KeyC},
	/*  d  */ {keyboard.KeyD},
	/*  e  */ {keyboard.KeyE},
	/*  f  */ {keyboard.KeyF},
	/*  g  */ {keyboard.KeyG},
	/*  h  */ {keyboard.KeyH},
	/*  i  */ {keyboard.KeyI},
	/*  j  */ {keyboard.KeyJ},
	/*  k  */ {keyboard.KeyK},
	/*  l  */ {keyboard.KeyL},
	/*  m  */ {keyboard.KeyM},
	/*  n  */ {keyboard.KeyN},
	/*  o  */ {keyboard.KeyO},
	/*  p  */ {keyboard.KeyP},
	/*  q  */ {keyboard.KeyQ},
	/*  r  */ {keyboard.KeyR},
	/*  s  */ {keyboard.KeyS},
	/*  t  */ {keyboard.KeyT},
	/*  u  */ {keyboard.KeyU},
	/*  v  */ {keyboard.KeyV},
	/*  w  */ {keyboard.KeyW},
	/*  x  */ {keyboard.KeyX},
	/*  y  */ {keyboard.KeyY},
	/*  z  */ {keyboard.KeyZ},
	/*  {  */ {Shift, keyboard.KeyLeftBrace},
	/*  |  */ {Shift, keyboard.KeyBackslash},
	/*  }  */ {Shift, keyboard.KeyRightBrace},
	/*  ~  */ {Shift, keyboard.KeyTilde},
	/* DEL */ nil,
}
